### ISSUE TITLE
How are files connected?

### ISSUE THREAD

**Issue by gcelano** [sigtyp/ST2022#10]
The logic of how the data are arranged in each folder in `ST2022/data/` is not completely clear to me. Is it possible to get an example showing how the files are related?

For example, I understand that the `test-x.tsv` files contain the field `?`, i.e., the one that needs to be predicted, and whose values are given in `solutions-x.tsv`. However, the files `training-x.tsv` seem to show a different logic, since there is no `?` to predict. Furthermore, what do the `result-x.tsv` files contain?

**Comment by LinguList** [comment]
Yes, the logic is that you:

1. train your model with the training data in whatever way (you can predict all items mutually, as our baseline does, make random samples, what you want)
2. predict the data in the test files
3. write predictions to a result-file
4. check against the solutions file

So if you want to train the model, how you do this with the training-data-file is left to you. Does that make the logic clearer?

**Comment by LinguList** [comment]
@gcelano, I assume you have also checked the file [`DOCUMENTATION.md`](https://github.com/sigtyp/ST2022/blob/v0.2/DOCUMENTATION.md), right? So we'd clarify this there.

**Comment by gcelano** [comment]
@LinguList Thanks! Now it's clearer to me 👍

**Comment by LinguList** [comment]
Super. I will leave this issue open until I added the information in the update version 1.0 with the surprise data.
