### ISSUE TITLE
Do we need metrics for fuzzy predictions?

### ISSUE THREAD

**Issue by LinguList** [sigtyp/ST2022#12]
It is clear that an algorithm can produce more than just one word form as a prediction. If enough people who want to participate want to work on fuzzy predictions, we would have to expand our current metrics to fuzzy predictions, which can be easily done.

**Comment by clefourrier** [comment]
That would be cool - my models tend to predict several results with associated confidence scores.

**Comment by LinguList** [comment]
For several words, all we need to do is to decide on the modification of the format (allowing to pass several solutions into one cell) and how the evaluation reacts on this (evaluating the average, or using some preference scoring system, as we employed in [Bodt and List 2022](https://doi.org/10.1075/dia.20009.bod)). We can offer two variants as well. 

A more complex case are those cases where one produces fuzzy segments, but here again, one can just take the cross-product of the fuzzy segments to produce all possible sequences and then evaluate.

**Comment by LinguList** [comment]
As @clefourrier was the only one who approached me for this, and I was recently informed that the methods now do not need fuzzy evaluation anymore, we will drop this for now and can mention it in the description later.
