### ISSUE TITLE
Question about the Shared Task's final deliverables

### ISSUE THREAD

**Issue by agutkin** [sigtyp/ST2022#15]
I have a question about the final delivery: As far as I understand from the task description we're supposed to release the software as well as the results on the surprise data in the CSV files in the format expected by the [sigtypst2022.py](https://github.com/sigtyp/ST2022/blob/main/src/sigtypst2022.py) tool. Is this correct?

**Comment by LinguList** [comment]
Yes, it must be in the formats indicated in the [Documentation](https://github.com/sigtyp/ST2022/blob/main/DOCUMENTATION.md#4-evaluating-results), since we also use this for evaluation.

**Comment by LinguList** [comment]
Evaluation should be done with the too, I even suggest we submit results for each group via github and evaluate them at once.
