### ISSUE TITLE
Evaluation of submitted system results

### ISSUE THREAD

**Issue by LinguList** [sigtyp/ST2022#17]
We need to decide about the structure of the folder in which results should be submitted. Ideally, we make an ID per team and ask them to push their data into the folders, using our namespaces maintained so far and then add the evaluation to the Makefile #16. 

Additionally, we may want to say that we also do plots of the data, which are probably useful, specifically when standardized.

**Comment by LinguList** [comment]
If teams prepare multiple system submissions, we need to ask teams to provide extended IDs, maybe composed of team-name and method.

**Comment by LinguList** [comment]
Since we are trying to add an evaluation for fuzzy predictions #12, each team needs to also provide information on whether they have one unique output or more than one, and if outputs should be ranked or not (compare how we handled ranked outputs in Bodt and List 2022, https://doi.org/10.1075/dia.20009.bod).  I imagine something like a nice overview table which we can write in the introduction to the shared task which will be co-authored by all participants.

**Comment by clefourrier** [comment]
Would it be interesting to also add BLEU as an evaluation metric?

**Comment by LinguList** [comment]
I am not sure, maybe? The evaluation metrics that were used so far, like edit distance, are flawed, as they do not take the structure or systematic errors into account. As I argue in a study from 2019 (https://doi.org/10.1515/tl-2019-0016, https://hcommons.org/deposits/item/hc:27897/), the B-Cubed scores account for this to some degree. 

So the question is: what would BLEU score add as a metric? Do they capture structure, systematic errors?

**Comment by clefourrier** [comment]
Hm, we discussed BLEU as being adapted to the task (in https://aclanthology.org/2021.findings-acl.75/ and https://aclanthology.org/2020.lt4hala-1.12.pdf): it captures part of the structure, as it counts the number of correct n-grams (from 1 to usually 4, needs to be weighted differently for short sequences) between 2 sequences.

To quote the second paper, "This is extremely interesting for our task, as sound changes can affect several
succeeding phones: this score gives us, not only the character error rate computed by the 1-gram, but also the errors
in the phone successions computed by the 2- to 4-grams in BLEU. "

**Comment by clefourrier** [comment]
WDYT?

**Comment by LinguList** [comment]
I am not sure. It may be good for translation, but sound correspondence regularity is not based on single words, but across words. And that is not captured, as far as I far as I understand...

**Comment by LinguList** [comment]
But I can check adding an implementation next week.

**Comment by clefourrier** [comment]
I meant that it captures word structure, not structure across word sets. I think it would be an interesting metric to add. If you want to add an implementation, the best would likely be too look at SacreBLEU, the reference implementation https://github.com/mjpost/sacrebleu

**Comment by LinguList** [comment]
Frankly, it seems like bleu scores are a bit of an overkill, given that words are very short and typical errors barely touch upon word order. I mean, going up to 4grams if a large number of morphemes has three sounds shows already that a detailed investigation of optimal features would be needed. But as we assemble here the largest collection of word prediction data ever, one can think of an extra study looking at metrics on the future and comparing them. If it is easy to implement, we can already add it (the reference implementation does not look modular enough for direct use on words, having lots of code for sentence processing). If not, one may mention the desire for more metrics to be tested in the future in the common introduction.

**Comment by clefourrier** [comment]
The reference implementation should be usable "as such", using our phone groups as words, and our words as sentences. (This is what we did in the above-mentioned previous papers, though with the Python version). We might need to use something along --tokenize none --force or equivalent to prevent extra processing. There should also be a possible smoothed weighting to prevent problems due to 4-gram for small words. I can check all that end of next week if you need a hand.

**Comment by LinguList** [comment]
Frankly, it seems like bleu scores are a bit of an overkill, given that words are very short and typical errors barely touch upon word order. I mean, going up to 4grams if a large number of morphemes has three sounds shows already that a detailed investigation of optimal features would be needed. But as we assemble here the largest collection of word prediction data ever, one can think of an extra study looking at metrics on the future and comparing them. If it is easy to implement, we can already add it (the reference implementation does not look modular enough for direct use on words, having lots of code for sentence processing). If not, one may mention the desire for more metrics to be tested in the future in the common introduction.

**Comment by clefourrier** [comment]
Hi, did you mean to post the exact same comment or is it an bug?

**Comment by LinguList** [comment]
Oh, did not notice that. Writing from smartphone while traveling, and gh showed it was not sent yet.

**Comment by clefourrier** [comment]
Np ^^

**Comment by LinguList** [comment]
I have now looked more closely at BLEU scores and my scepticism remains, as their major strength, concentrating only on precision, lies in the possibility to compare ONE prediction against MANY possible good answers. In word prediction, we have only ONE good word (=one answer). So we can afford to use recall as well.

So I would argue the major intention behind BLEU scores does not conform well to the idea behind word prediction.

Nevertheless, the scores are easy to implement for *n* n-grams, using LingPy's `get_n_ngram` function, so it does not cost a lot to add the evaluation scores.

```python
def bleu_score(word, reference, n=4, weights=None, trim=False):
    """
    Compute the BLEU score for predicted word and reference.
    """

    if not weights:
        weights = [1/n for x in range(n)]
    
    scores = []
    for i in range(1, n+1):
        
        new_wrd = list(get_n_ngrams(word, i))
        new_ref = list(get_n_ngrams(reference, i))
        if trim and i > 1:
            new_wrd = new_wrd[i-1:-(i-1)]
            new_ref = new_ref[i-1:-(i-1)]

        clipped, divide = [], []
        for itm in set(new_wrd):
            clipped += [new_ref.count(itm)]
            divide += [new_wrd.count(itm)]
        scores += [weights[i-1] * sum(clipped) / sum(divide)]

    return sum(scores)
```

This yields scores as we find them in the example paper from [Papineni et al. (2022)](https://aclanthology.org/P02-1040.pdf). The `trim` keyword decides if we take start symbols for n-grams into account or not (`get_n_ngrams` will always add n-1 start and end-n-grams for n-grams of size n). It may not be needed.

**Comment by clefourrier** [comment]
You can also compare many predictions to one answer (which is what we do in our paper), which is interesting for models which learn the inherent ambiguity of the task and can produce with a high confidence several answers that are plausible.

**Comment by clefourrier** [comment]
I also think that a panel of scores for this task will be interesting anyway, as there is no definite "perfect metric", especially not for this task.

**Comment by LinguList** [comment]
Well, this bleu score implementation is straightforward and does not add much complexity to the whole endeavor. I'd leave the trim-feature to False, as this avoids that it casts errors on short words, and we will have a rough estimate and see if it is much different from edit distance.

For fuzzy reconstructions with multiple results, I would not use it, as it is measuring precision, and this would be recall, if you swap reference and candidate, so I'll add another implementation here, which also allows for ranked weights if needed and otherwise averages results as we did in our paper on prediction in Diachronica.

**Comment by LinguList** [comment]
Update, I forgot to add the penalty for short words, but now, it turns out, the code's result is identical with the `sentence_bleu` from the nltk package, which means we have a bleu_score implementation here:

```python
def bleu_score(word, reference, n=4, weights=None, trim=False):
    """
    Compute the BLEU score for predicted word and reference.
    """

    if not weights:
        weights = [1/n for x in range(n)]
    
    scores = []
    for i in range(1, n+1):
        
        new_wrd = list(get_n_ngrams(word, i))
        new_ref = list(get_n_ngrams(reference, i))
        if trim and i > 1:
            new_wrd = new_wrd[i-1:-(i-1)]
            new_ref = new_ref[i-1:-(i-1)]

        clipped, divide = [], []
        for itm in set(new_wrd):
            clipped += [new_ref.count(itm)]
            divide += [new_wrd.count(itm)]
        scores += [sum(clipped) / sum(divide)]

    # calculate arithmetic mean
    out_score  = 1
    for weight, score in zip(weights, scores):
        out_score = out_score * (score ** weight)
    
    if len(word) > len(reference):
        bp = 1
    else:
        bp = math.e ** (1-(len(reference)/len(word)))
    return bp * (out_score ** (1/sum(weights)))
```
