### ISSUE TITLE
Are the results for the original (non-surprise) training set also required?

### ISSUE THREAD

**Issue by agutkin** [sigtyp/ST2022#29]
I noticed that the `systems` template directory also has results for the original training set of 10 language groups. Do we need to generate the results for these as well?

@rwsproat, @ckirov

**Comment by LinguList** [comment]
I'd find this interesting, and it would make it more complete.

**Comment by agutkin** [comment]
Thanks! We're started working on this. May not make the strict deadline, but hopefully the results for the training data are going to be finished in two or three days. Our fifth system (`n2`) trains for ages on my box.

**Comment by LinguList** [comment]
This is absolutely fine. My hope is to provide individual and general 
results on Wednesday, April 27 for the surprise data and all systems, 
using again a makefile that does this in one run with code from our 
library and automated plots with matplotlib. So once training data is 
available, this can then also be added, but training results are more 
for us to check how things perform in general, etc., I would say we do 
not need to report them in the papers for each system.
