### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by gcelano** [sigtyp/ST2022#44]
I am wondering whether the script to calculate the results can be made available: since I have some other data, I would be curious to see what the results are.

In the file https://github.com/sigtyp/ST2022/tree/main/results#detailed-results-for-all-datasets , I would suggest to change the sentence:

`In some cases, the teams also could not provide all data for the individual training sets, due to time limitations and for other reasons.`

with a sentence clarifying that the 0 scores in the tables are only (as far as I know) due to missing data: otherwise, a 0 score might be interpreted as the (bad) result of a certain model.

**Comment by LinguList** [comment]
Yep, you are right. Or the perfect score of an edit distance of 0.

**Comment by LinguList** [comment]
The script to calculate the results is in fact available with this package.

**Comment by LinguList** [comment]
Have you checked the DOCUMENTATION.md file? This file contains all info, also on how to use the library *internally*, so you call the paths etc. from a Python script and then run all evaluations from there.

**Comment by LinguList** [comment]
I have even added the BLEU scores to [lingrex](https://github.com/lingpy/lingrex), so they are available in the form of an external command.

**Comment by LinguList** [comment]
And the function to compare two files is here:

https://github.com/sigtyp/ST2022/blob/114faa490122b708b234fc28014425e3d821b347/src/sigtypst2022.py#L495-L533

**Comment by LinguList** [comment]
And plotting for several scores, etc. is here:

https://github.com/sigtyp/ST2022/blob/114faa490122b708b234fc28014425e3d821b347/src/sigtypst2022.py#L697-L775
