### ISSUE TITLE
Add Fourrier et al 2021 as reference

### ISSUE THREAD

**Issue by clefourrier** [sigtyp/ST2022#9]
Hi, 
We wrote a paper on cognate/reflex prediction using machine translation techniques, which could be relevant.
- Paper: [Can Cognate Prediction Be Modelled as a Low-Resource Machine Translation Task?](https://aclanthology.org/2021.findings-acl.75.pdf)
- Citation: Clémentine Fourrier, Rachel Bawden and Benoît Sagot, Can Cognate Prediction Be Modelled as a Low-Resource Machine Translation Task?, In Findings of the Association for Computational Linguistics: ACL-IJCNLP 2021, pages 847--861, Association for Computational Linguistics
- Full code and datasets: https://github.com/clefourrier/CopperMT

**Comment by LinguList** [comment]
Thanks, we'll add this when updating version 1.0 with the test data. What is different from our task is that this is a bilingual setting, while our task is multilingual.

**Comment by clefourrier** [comment]
Cool!

However, this paper especially studies the impact of multilinguality on reflex prediction: the best performing models trained are multilingual, and learn to go from all language to all, as the multilingual training constrains the learned representation to be common to all languages. 

Please tell me if I misunderstood something from your comment.

**Comment by LinguList** [comment]
Yes, true, sorry, I did not read the paper, only checked the data, and I assumed it was another study I had read in the past. You are completely right. 


So is your system applicable to the shared task?

**Comment by clefourrier** [comment]
No problem.

Yes, it should be!

**Comment by LinguList** [comment]
Then we look very much forward to your contribution :)
